** gem environment

https://www.cygwin.com/ml/cygwin/2014-11/msg00390.html

gem environment

*** 

[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [x86_64-cygwin]
  - INSTALLATION DIRECTORY: /home/Administrator/.gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby.exe
  - EXECUTABLE DIRECTORY: /home/Administrator/bin
  - SPEC CACHE DIRECTORY: /home/Administrator/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-cygwin
  - GEM PATHS:
     - /home/Administrator/.gem/ruby
     - /usr/share/gems
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/Administrator/bin
     - .
     - /c/cygwin64/usr/local/bin
     - /c/cygwin/usr/local/bin
     - /c/cygwin64/bin
     - /c/cygwin/bin
     - /home/Administrator/bin
     - .
     - /c/cygwin64/usr/local/bin
     - /c/cygwin/usr/local/bin
     - /c/cygwin64/bin
     - /c/cygwin/bin
     - /home/Administrator/bin
     - .
     - /c/cygwin64/usr/local/bin
     - /c/cygwin/usr/local/bin
     - /c/cygwin64/bin
     - /c/cygwin/bin
     - /usr/local/bin
     - /usr/bin
     - /c/tools/ruby21/bin
     - /c/Windows/system32
     - /c/Windows
     - /c/Windows/System32/Wbem
     - /c/Windows/System32/WindowsPowerShell/v1.0
     - /c/Program Files/Amazon/cfn-bootstrap
     - /c/ProgramData/chocolatey/bin
     - /c/Program Files (x86)/MySQL/MySQL Utilities
     - /c/Program Files (x86)/MySQL/MySQL Utilities/Doctrine extensions for PHP
     - /c/Program Files (x86)/QuickTime/QTSystem
     - /c/MySQL/bin
     - /c/php
     - /c/Program Files (x86)/Git/cmd
     - /c/Program Files/nodejs
     - /c/tools/python
     - /c/Program Files (x86)/Nmap
     - /usr/bin
     - /c/SLS_DB/tools
     - /c/SLS_DB/tools/Junction
     - /c/MySQL/bin
     - /c/Users/Administrator/AppData/Roaming/npm
     - /c/libjpeg-turbo64/bin
     - /home/Administrator/.rvm/bin
     - /home/Administrator/.rvm/bin
     - /home/Administrator/.rvm/bin
[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ 

** devkit for windows

https://github.com/oneclick/rubyinstaller/wiki/Development-Kit


DevKit Overview

The DevKit is a toolkit that makes it easy to build and use native C/C++
extensions such as RDiscount and RedCloth for Ruby on Windows.

Simply download, double-click, choose an installation directory, run the
Ruby install helper script, possibly tweak a config.yml file for your
system specifics, and you’re ready to start using native Ruby
extensions.

** running ocra on cygwin


cygwin ruby undefined method path for .gem/ruby


undefined method path for .gem/ruby : String (NoMethodError)

undefined method `path' for "/home/Administrator/.gem/ruby":String (NoMethodError)



/home/Administrator/.gem/ruby/gems/ocra-1.3.5/bin/ocra:41

:in `relative_path_from': undefined method `path' for "/home/Administrator/.gem/ruby":String (NoMethodError)

/home/Administrator/.gem/ruby/gems/ocra-1.3.5/bin/ocra:41:in `relative_path_from': undefined method `path' for "/home/Administrator/.gem/ruby":String (NoMethodError)


[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ make
ocra parse.rb
/home/Administrator/.gem/ruby/gems/ocra-1.3.5/bin/ocra:19: warning: already initialized constant File::ALT_SEPARATOR
=== Loading script to check dependencies
=== Attempting to trigger autoload of Gem::ConfigFile
=== Attempting to trigger autoload of Gem::DependencyList
=== Attempting to trigger autoload of Gem::DependencyResolver
=== Attempting to trigger autoload of Gem::Installer
=== Attempting to trigger autoload of Gem::RequestSet
=== Attempting to trigger autoload of Gem::Source
=== Attempting to trigger autoload of Gem::SourceList
=== Attempting to trigger autoload of Gem::SpecFetcher
=== Attempting to trigger autoload of CGI::HtmlExtension
=== Detected gem ocra-1.3.5 (loaded, files)
=== 	6 files, 191333 bytes
=== Detected gem iniparse-1.4.0 (loaded, files)
=== 	9 files, 29455 bytes
=== Including 53 encoding support files (3255791 bytes, use --no-enc to exclude)
/home/Administrator/.gem/ruby/gems/ocra-1.3.5/bin/ocra:41:in `relative_path_from': undefined method `path' for "/home/Administrator/.gem/ruby":String (NoMethodError)
	from /home/Administrator/.gem/ruby/gems/ocra-1.3.5/bin/ocra:779:in `block in build_exe'
	from /home/Administrator/.gem/ruby/gems/ocra-1.3.5/bin/ocra:762:in `each'
	from /home/Administrator/.gem/ruby/gems/ocra-1.3.5/bin/ocra:762:in `build_exe'
	from /home/Administrator/.gem/ruby/gems/ocra-1.3.5/bin/ocra:1177:in `block in <top (required)>'
Makefile:11: recipe for target 'parse.exe' failed
make: *** [parse.exe] Error 1
[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ 

** update_rubygems

update_rubygems

[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ update_rubygems
RubyGems 2.4.8 installed
Parsing documentation for rubygems-2.4.8
Installing ri documentation for rubygems-2.4.8

=== 2.4.8 / 2015-06-08

Bug fixes:

 * Tightened API endpoint checks for CVE-2015-3900


------------------------------------------------------------------------------

RubyGems installed the following executables:
	/usr/bin/gem

Ruby Interactive (ri) documentation was installed. ri is kind of like man 
pages for ruby libraries. You may access it like this:
  ri Classname
  ri Classname.class_method
  ri Classname#instance_method
If you do not wish to install this documentation in the future, use the
--no-document flag, or set it as the default in your ~/.gemrc file. See
'gem help env' for details.

[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ 

** 

[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ gem --version
2.4.8
[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-cygwin]
[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ 

** gem update --system

gem update --system

[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.4.8.gem (100%)
Successfully installed rubygems-update-2.4.8
Parsing documentation for rubygems-update-2.4.8
Installing ri documentation for rubygems-update-2.4.8
Installing darkfish documentation for rubygems-update-2.4.8
Done installing documentation for rubygems-update after 2 seconds
Parsing documentation for rubygems-update-2.4.8
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.4.8
RubyGems 2.4.8 installed
Parsing documentation for rubygems-2.4.8
Installing ri documentation for rubygems-2.4.8

=== 2.4.8 / 2015-06-08

Bug fixes:

 * Tightened API endpoint checks for CVE-2015-3900

=== 2.4.7 / 2015-05-14

Bug fixes:

 * Backport: Limit API endpoint to original security domain for CVE-2015-3900.
  Fix by claudijd


------------------------------------------------------------------------------

RubyGems installed the following executables:
	/usr/bin/gem

Ruby Interactive (ri) documentation was installed. ri is kind of like man 
pages for ruby libraries. You may access it like this:
  ri Classname
  ri Classname.class_method
  ri Classname#instance_method
If you do not wish to install this documentation in the future, use the
--no-document flag, or set it as the default in your ~/.gemrc file. See
'gem help env' for details.

RubyGems system software updated
[Administrator@tl2:/tmp/ruby-practice/read-write-ini(cygwin)]$ 

